# Estructuras Repititivas Loops
Las estructururas repetitivas o cíclicas son aquellos bloques de código que nos permiten acceder o monitorear un bloque de código particular para que ejecute una serie de instrucciones hasta que se cumpla una condición de salida de la estructrura repetitiva.

Vamos a analizar e implementar dos estructuras repetitivas claves:
+ __while__ loops
+ __for__ loops

# Estructura Repetitiva Mientras (While Loops)
### La sintaxis de esta estructura es la siguiente:
`while *condición*
    *cuerpo o bloque de código a ejecutar*
end`

Por ejemplo, vamos a mostrar los nùmeros del 1 al 10, definiendo una variable __n__ la cual se inicializa con __0__, donde vamos aumentando de uno en uno su valor hasta que se muestren los números del 1 al 10

In [3]:
n = 0
while n < 10
    n+=1
    # n+=1 es una forma alternativa de decir n = n + 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


Otra actividad que podemos realizar con las __estructuras repetitivas__ es iterar un __array__ para mostrar los elementos que tenemos almacenados en ese arreglo

In [6]:
# Arreglo que almacena los cursos que estoy viendo en el semestre lectivo
myCourses = ["Inteligencia Artificial", "Simulación I", "Calculo Diferencial", "Estadística Descriptiva"]
# la variable i determinará el inicio del ciclo
i = 1
# con la función length() podemos capturar la dimensión de un array
while i <= length(myCourses)
    # usamos una variable course auxiliar para capturar cada uno de los cursos
    course = myCourses[i]
    # Imprimimos en pantalla el curso que estamos viendo
    println("Este semestre estás viendo el curso de $course")
    # Aumentamos la variable en uno (contador) para poder continuar con el transcurso del ciclo mientras
    i += 1
end

Este semestre estás viendo el curso de Inteligencia Artificial
Este semestre estás viendo el curso de Simulación I
Este semestre estás viendo el curso de Calculo Diferencial
Este semestre estás viendo el curso de Estadística Descriptiva


> Con los ciclos __Mientras__ es muy importante recordar que dentro del cuerpo de ejecución del ciclo se debe aumentar o decrementar la variable controladora (__esta variable es la que se encarga en romper el ciclo__) ya qué, si esto no se realiza quedaríamos en un __ciclo infinito__

# Estructura Repetitiva Para (For Loops)
### La sintaxis de esta estructura es la siguiente:
`for *variable inicial* in *iteración del ciclo*
    *cuerpo o bloque de código a ejecutar*
end`

En esta serie de ejemplos podemos realizar las mismas actividades y resultados que obtuvimos haciendo uso de la estructura repetitiva __Mientras__

In [7]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [8]:
for course in myCourses
    println("Este semestre estás viendo el curso de $course")
end

Este semestre estás viendo el curso de Inteligencia Artificial
Este semestre estás viendo el curso de Simulación I
Este semestre estás viendo el curso de Calculo Diferencial
Este semestre estás viendo el curso de Estadística Descriptiva


> En Julia podemos reemplazar __in__ por `=` o `∈`

In [12]:
for n = 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [13]:
for n ∈ 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


Ahora vamos a usar los ciclos __for__ para crear algunas tablas adicionales, donde los valores de cada entrada es la suma de los indices de su fila y columna

In [14]:
# Inicializando las dimensiones del arreglo, puedo separar por comas las variables para que en una sola linea inicialice varias variables
n, m = 5, 5
# Es buena práctica declarar e inicializar nuestras variables, en este caso vamos a crear una matriz llamada A llena de ceros haciendo uso de la función zeros()
A = zeros(n,m)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [17]:
for i in 1:n
    for j in 1:m
        A[i, j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

> Julia nos provee una sintáxis más práctica y corta __syntactic sugar__ para expresar el anterior anidamiento de los ciclos __for__

In [19]:
B = zeros(n,m)
for i in 1:n , j = 1:m
    B[i,j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Ahora, al entender que podemos usar __azucar sintáctico__ Julia provee una forma magnífica de generar la tabla anterior con un __array comprehension__

In [20]:
C = [ i + j for i in 1:n, j ∈ 1:m]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

En el siguiente ejemplo, vamos a embeber un __array comprehension__ en un __foor loop__, generando tablas adicionales que creciendo su tamaño

In [21]:
for n in 1:10
    D = [ i + j for i in 1:n, j = 1:n]
    display(D)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20